fruits={"orange","apple","mango","banana","apple"}
juice={"orange"}
#print(fruits.intersection(juice))
#print(fruits.union(juice))
#print(juice.issubset(fruits))
#print(juice.issuperset(fruits))
print(fruits.difference(juice))
#fruits.add("grapes")
#fruits.remove("pine")
#fruits.discard("opineapple")
#print(fruits)
